"""empty message

Revision ID: 2dea0c060f4a
Revises: 65055bc37c49
Create Date: 2019-06-05 12:58:08.010197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dea0c060f4a'
down_revision = '65055bc37c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('norms', sa.Column('default', sa.Float(), nullable=True))
    op.add_column('norms', sa.Column('defect', sa.Float(), nullable=True))
    op.add_column('norms', sa.Column('major', sa.Float(), nullable=True))
    op.add_column('norms', sa.Column('minor', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('norms', 'minor')
    op.drop_column('norms', 'major')
    op.drop_column('norms', 'defect')
    op.drop_column('norms', 'default')
    # ### end Alembic commands ###
