"""empty message

Revision ID: 35583092d4b8
Revises: 6ff11a5b1b22
Create Date: 2019-06-05 12:55:24.487447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35583092d4b8'
down_revision = '6ff11a5b1b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'value')
    # ### end Alembic commands ###
