"""initial migration

Revision ID: 4798ee390777
Revises: None
Create Date: 2019-05-21 17:01:04.433784

"""

# revision identifiers, used by Alembic.
revision = '4798ee390777'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('about', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('location', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'location')
    op.drop_column('companies', 'about')
    # ### end Alembic commands ###
