"""empty message

Revision ID: 6ff11a5b1b22
Revises: 
Create Date: 2019-06-05 12:54:03.139791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff11a5b1b22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
